### ISSUE TITLE
Deprecated stylefmt dependency in gulp-stylefmt

### ISSUE THREAD

**Issue by ronilaukkarinen** [digitoimistodude/air-light#21]
Stylefmt has a known bug that causes stylefmt not to run (too old stylelint version). The bug is in effect if other than `stylelint-config-primer` is used. Air switched to [stylelint-config-wordpress](https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/) after 4.3.1 so this bug exists.

Steps to fix in [this issue](https://github.com/morishitter/stylefmt/issues/334#issuecomment-436552167). This won't be fixed until stylefmt is updated to the repo, but adding this issue as a note to myself.

```` bash
➜  air-light (master) gulp watch
[10:47:01] Using gulpfile ~/Projects/airdev/content/themes/air-light/gulpfile.js
[10:47:01] Starting 'browsersync'...
[10:47:01] Finished 'browsersync' after 14 ms
[10:47:01] Starting 'watch'...
[10:47:01] Finished 'watch' after 26 ms
[Browsersync] Proxying: http://airdev.test
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3002
    External: http://192.168.1.233:3002
 --------------------------------------
          UI: http://localhost:3003
 UI External: http://localhost:3003
 --------------------------------------
[Browsersync] Watching files...
[10:47:20] Starting 'styles'...
[10:47:20] Finished 'styles' after 20 ms
[clean-css] Original size: 149271 bytes
[clean-css] Minified size: 114521 bytes
[clean-css] Time spent on minification: 751 ms
[clean-css] Compression efficiency: 23.279806526384895 %
[Browsersync] 1 file changed (global.min.css)
Error: Undefined rule font-family-no-missing-generic-family-keyword
    at module.exports (/Users/rolle/Projects/airdev/content/themes/air-light/node_modules/gulp-stylefmt/node_modules/stylelint/lib/utils/configurationError.js:8:27)
    at Object.keys.forEach.ruleName (/Users/rolle/Projects/airdev/content/themes/air-light/node_modules/gulp-stylefmt/node_modules/stylelint/lib/augmentConfig.js:279:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/Users/rolle/Projects/airdev/content/themes/air-light/node_modules/gulp-stylefmt/node_modules/stylelint/lib/augmentConfig.js:275:29)
    at augmentConfigBasic.then.then.then.then.augmentedConfig (/Users/rolle/Projects/airdev/content/themes/air-light/node_modules/gulp-stylefmt/node_modules/stylelint/lib/augmentConfig.js:84:12)
[Browsersync] 1 file changed (global.css)
````

**Comment by ronilaukkarinen** [comment]
Got rid of gulp-stylefmt as a dependency in 5.4.6 in favor to [vscode-stylefmt](https://github.com/mrmlnc/vscode-stylefmt) so closing this.
