### ISSUE TITLE
style lint reserved word error on gulp watch?

### ISSUE THREAD

**Issue by Tanmccuin** [digitoimistodude/air-light#48]
Just installed a new test environment to look at the recent changes to the theme, and after npm installing and find/replacing the namespace (air-light) i attempted to run my first gulp watch and received this error that i haven't run into before. Curious if this is a new bug or an issue you may be aware of and have some advice on?

` 
gulp watch                                                                                                      ~
/themes/air-light/node_modules/stylelint/node_modules/cosmiconfig/dist/Explorer.js:54
    for await (const place of this.config.searchPlaces) {
        ^^^^^

SyntaxError: Unexpected reserved word
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)

`

**Comment by Tanmccuin** [comment]
I brought Node up to date and rebuilt node-sass - all good.

**Comment by ronilaukkarinen** [comment]
Yes, we've had package changes lately. Sometimes it's best to try to clean up node_modules (`rm -rf node_modules`) and rebuild all packages with `npm install`. Glad you got it solved!
